version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-7-jdk
      - java -version
      - apt-get install -y maven
  pre_build:
    version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-7-jdk
      - java -version
      - apt-get install -y maven
  build:
    commands:
      - echo Build started on `date`
      - apt-get install -y maven
      - mvn clean install              
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...   
  artifacts:
  files:
    - messageUtil-1.0.jar
  discard-paths: yes
